### ISSUE TITLE
计算时间问题

### ISSUE THREAD

**Issue by wangyuan111** [CuberrChen/STDCNet-Paddle#1]
你好，我在paddleseg中测试了推理耗时，图像大小480*640，GPU是3090，每张耗时17ms，这个和原文里差别很大，请问你有没有测试过耗时相关问题

**Comment by CuberrChen** [comment]
@wangyuan111
你好，我并没有做过相关测试。另外，现在这个仓库的版本不是最终版本。你可以去PaddleSeg官方仓库的develop分支试用优化过后的版本，我看那边已经提供了。另外呢，原文的指标我之前看好像是经过tensorRT之后的指标。

**Comment by wangyuan111** [comment]
好的 问题已在PaddleSeg官方仓库被解答 谢谢
